# Generated by Django 2.0.2 on 2018-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='mp3', max_length=10),
        ),
    ]
